### ISSUE TITLE
Migrate to using githup pages?

### ISSUE THREAD

**Issue by psiinon** [OWASP/OWASP-VWAD#17]
Suggestion - how about we move the 'db' off https://www.owasp.org/index.php/OWASP_Vulnerable_Web_Applications_Directory_Project#tab=Off-Line_apps and instead host it on github pages.
The OWASP page would then just point to those pages.
Advantages - we'd just need to maintain one format and only need to support editing via PRs rather than also having to support direct media wiki editing.

**Comment by bkimminich** [comment]
Alternatively we could also host it in the fashion of an [awesome list](https://github.com/sindresorhus/awesome) directly on GitHub. But a nicely formatted GitHub page would probably increase overall reach. On the other hand, we learned from a recent mailing list discussion that many corporations block GitHub. So we'd at least need a proxy domain for that gh-page or some people won't be able to see the VWAD any more.

**Comment by jhaddix** [comment]
A GitHub pages implementation would offer better production options and reach than and `awesome list` imo.

**Comment by raulsiles** [comment]
Probably we can manage both, create our own web page under GitHub pages (still waiting for other implications and requirements associated to the current OWASP web pages where OWASP VWAD is currently hosted), and get it linked from Awesome Lists.

**Comment by raulsiles** [comment]
The current VWAD web pages hosted in the OWASP Wiki (at https://www.owasp.org/index.php/OWASP_Vulnerable_Web_Applications_Directory_Project) are completely outdated with respect to the latest changes added to the JSON files in GitHub. 

We need to decide where and how we want to host the final webpages, or at least update the conversion scripts (at https://github.com/OWASP/OWASP-VWAD/tree/master/bin) to translate from/to JSON (rather than from the old TSV format) to the Wiki format.

Votes for the location of the web pages (please, review previous comments): OWASP Wiki or GitHub? Pros and cons of each?

**Comment by psiinon** [comment]
Some people have mentioned to me that they really like the fact that the info is on OWASP as its less likely to be blocked and has more 'authority'.
Having said that, I think github pages would be a good idea ;)
Note that we do have scripts for generating the OWASP wiki pages (and vise-versa) but they have to be run manually and I havnt tried running them for a while :/
https://github.com/OWASP/OWASP-VWAD/tree/master/bin

**Comment by bkimminich** [comment]
If we spend a few OWASP-$ on a nice domain the authority aspect should survive the move to GH-pages, no?

**Comment by bkimminich** [comment]
Closing this one in favor of #75
