### ISSUE TITLE
Migrate to www-project-vulnerable-web-applications-directory

### ISSUE THREAD

**Issue by bkimminich** [OWASP/OWASP-VWAD#75]
With the new Jekyll-powered OWASP website it should be easy to dynamically parse the `JSON` data sets and render each in its own tab on https://owasp.org/www-project-vulnerable-web-applications-directory.

## Tasks
* Find out if Jekyll can load JSON from this repo into `www-project-vulnerable-web-applications-directory`
  * If not, either move the files over (effectively sunsetting this repo with all its ⭐️s...) or
  * Implement an automatic copy job e.g. via Travis-CI or GH-Actions
* Add a tab per category and dynamically create a table on each from the `JSON` data

**Comment by bkimminich** [comment]
https://jekyllrb.com/docs/datafiles does not mention external data sources, but there's at least this plugin that promises to do what we would need: https://github.com/brockfanning/jekyll-get-json

**Comment by kingthorin** [comment]
All 3 lists are now online: https://owasp.org/www-project-vulnerable-web-applications-directory/
I had tried to make them separate tabs but the build kept failing, likely because of mixed HTML/MD (which I will tackle at some point in the future). For now at least they're online once again and up-to-date.

(The JSON files were separately pushed to the www-project repo.)

**Comment by kingthorin** [comment]
The tab issue has been sorted out and fixed/implemented.

**Comment by kingthorin** [comment]
I guess this can be closed.

Any chance someone could hook me up with additional permissions here.

**Comment by thc202** [comment]
Talking about permissions, the wiki should be disabled (or restrict who can edit).
